name: CI

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  ci:
    name: lint & test

    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.5
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Install dependencies
        run: flutter pub get

      - run: flutter analyze

      - run: flutter test
